disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - comma
#  - control_statement
- closure_parameter_position
#  - file_length
- force_cast
- force_try
#  - function_body_length
- function_parameter_count
#  - leading_whitespace
#  - line_length
#  - nesting
#  - operator_whitespace
#  - opening_brace
#  - return_arrow_whitespace
#  - statement_position
#  - todo
#  - trailing_newline
#  - trailing_semicolon
#  - trailing_whitespace
- type_body_length
- type_name
- valid_docs
- variable_name
- variable_name_min_length
- nesting
- multiple_closures_with_trailing_closure
#  - variable_name_max_length
- unused_closure_parameter
excluded: # paths to ignore during linting. overridden by `included`.
- Carthage
- Pods
- fastlane
- XLProjectName/Helpers/R-Swift/R.generated.swift
# parameterized rules can be customized from this configuration file
file_length:
- 700
- 1000
line_length:
- 250
- 250
# parameterized rules are first parameterized as a warning level, then error level.
function_body_length:
- 150 # warning
- 200 # error
type_body_length:
- 300 # warning
- 400 # error
variable_name_max_length:
- 30 # warning
- 40 # error
variable_name_min_length:
- 2 # warning
- 1 # error
